# This is the configuration file for d≈çteki, a tool to easily add dynamic content to your GitHub profile.
# For more information and documentation, visit https://doteki.org/

[sections.blog]
plugin = "feed"
url = "https://osc.garden/atom.xml"
n = 8
show_date = false
prepend_text = "## Latest blog posts\n\n"
append_text = "\n\nMore on [osc.garden](https://osc.garden)"

[sections.notes]
plugin = "feed"
url = "https://osc.garden/notes/atom.xml"
n = 3
show_date = false
prepend_text = "## Recently updated notes\n\n"
append_text = "\n\nSee [more notes](https://osc.garden/notes)"

[sections.lastfm]
plugin = "lastfm"
username = "welpo"
type = "artists"
period = "7day"
n = 3
inline = true
preset = "comma_and"
